INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("3C 66A");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("3C 84");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("3C 111");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("3C 279");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("3C 345");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("3C 371");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("MG4 2001+43");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("AO0235");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("B2 1308");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("CTA26");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("CTA102");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("Mkn421");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("Mkn501");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("OJ049");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("OJ248");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("OT081");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("PKS0420");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("PKS0528");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("PKS0735");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("PKS1055");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("PKS1222");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("PKS1406");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("PKS1510");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("Q0650");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("Q0836");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("Q1156");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("Q1611");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("Q1633");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("Q1739");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("S4 0954");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("S4 1030");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("W Com");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("PV Cep");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("J2103");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("HBC 722");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("CI Cam");
INSERT INTO drupal7.phot_arch_spbu_objects (name) VALUES ("4U 0115");